// Локальная i18n компонента LearningSession — только данные переводов (langGuard-страж и паритет ключей сохранены).
import { langGuard } from "../../interface/i18nGuard.js";

export const T = langGuard({
    ru: { batchDone: "Партия форм сдана — возвращаются новые слова!", done: "Сессия завершена", acc: "верно", cardsShown: "карточек показано", shown: "показано", masteredLabel: "Выучено", protectedLabel: "Защищено", protectedTypoLabel: "Защищено с опечаткой", of: "из", perSession: "за сессию", levelTo: "До уровня", maxLevel: "Максимальный уровень 🎉", streak: "серия", days: "дн.", left: "ещё на сегодня", leftZero: "Дневная цель выполнена 🎯", examNote: "Готова пачка слов — сдай экзамен, чтобы открыть новые", more: "Ещё сессия", finish: "В Учёбу", words: "слов", loading: "Готовим сессию…", empty: "Пока нечего учить — добавь слова в Учёбу" },
    en: { batchDone: "Forms batch complete — new words are coming back!", done: "Session complete", acc: "correct", cardsShown: "cards shown", shown: "shown", masteredLabel: "Learned", protectedLabel: "Protected", protectedTypoLabel: "Protected with a typo", of: "of", perSession: "this session", levelTo: "To level", maxLevel: "Top level 🎉", streak: "streak", days: "d.", left: "left for today", leftZero: "Daily goal done 🎯", examNote: "A word pack is ready — pass the exam to unlock new ones", more: "One more", finish: "To Study", words: "words", loading: "Building session…", empty: "Nothing to learn yet — add words to Study" },
    ukr: { batchDone: "Партію форм складено — повертаються нові слова!", done: "Сесію завершено", acc: "правильно", cardsShown: "карток показано", shown: "показано", masteredLabel: "Вивчено", protectedLabel: "Захищено", protectedTypoLabel: "Захищено з опискою", of: "з", perSession: "за сесію", levelTo: "До рівня", maxLevel: "Максимальний рівень 🎉", streak: "серія", days: "дн.", left: "ще на сьогодні", leftZero: "Денну ціль виконано 🎯", examNote: "Пачка слів готова — склади екзамен, щоб відкрити нові", more: "Ще сесія", finish: "До Навчання", words: "слів", loading: "Готуємо сесію…", empty: "Поки нема чого вчити — додай слова до Навчання" },
    pl: { batchDone: "Partia form zaliczona — wracają nowe słowa!", done: "Sesja zakończona", acc: "poprawnie", cardsShown: "kart pokazano", shown: "pokazano", masteredLabel: "Nauczono", protectedLabel: "Chronione", protectedTypoLabel: "Chronione z literówką", of: "z", perSession: "w sesji", levelTo: "Do poziomu", maxLevel: "Najwyższy poziom 🎉", streak: "seria", days: "dn.", left: "na dziś", leftZero: "Cel dzienny osiągnięty 🎯", examNote: "Paczka słów gotowa — zdaj egzamin, aby odblokować nowe", more: "Jeszcze raz", finish: "Do Nauki", words: "słów", loading: "Przygotowujemy sesję…", empty: "Na razie nie ma czego się uczyć — dodaj słowa do Nauki" },
    lt: { batchDone: "Formų partija įveikta — grįžta nauji žodžiai!", done: "Sesija baigta", acc: "teisingai", cardsShown: "kortelių parodyta", shown: "parodyta", masteredLabel: "Išmokta", protectedLabel: "Apsaugota", protectedTypoLabel: "Apsaugota su klaida", of: "iš", perSession: "sesijoje", levelTo: "Iki lygio", maxLevel: "Aukščiausias lygis 🎉", streak: "serija", days: "d.", left: "šiandienai", leftZero: "Dienos tikslas pasiektas 🎯", examNote: "Žodžių paketas paruoštas — išlaikyk egzaminą, kad atrakintum naujus", more: "Dar viena", finish: "Į Mokymąsi", words: "žodžių", loading: "Ruošiame sesiją…", empty: "Kol kas nėra ko mokytis — pridėk žodžių į Mokymąsi" },
    lv: { batchDone: "Formu partija nokārtota — atgriežas jauni vārdi!", done: "Sesija pabeigta", acc: "pareizi", cardsShown: "kartiņu parādīts", shown: "parādīts", masteredLabel: "Apgūts", protectedLabel: "Aizsargāts", protectedTypoLabel: "Aizsargāts ar pārrakstīšanos", of: "no", perSession: "šajā sesijā", levelTo: "Līdz līmenim", maxLevel: "Augstākais līmenis 🎉", streak: "sērija", days: "d.", left: "atlicis šodien", leftZero: "Dienas mērķis sasniegts 🎯", examNote: "Vārdu paka gatava — nokārto eksāmenu, lai atvērtu jaunus", more: "Vēl viena", finish: "Uz Mācībām", words: "vārdi", loading: "Sagatavojam sesiju…", empty: "Pagaidām nav ko mācīties — pievieno vārdus Mācībām" },
    ar: { batchDone: "أُنجزت دفعة الصيغ — تعود الكلمات الجديدة!", done: "اكتملت الجلسة", acc: "صحيح", cardsShown: "بطاقات معروضة", shown: "معروضة", masteredLabel: "متعلَّمة", protectedLabel: "محميّة", protectedTypoLabel: "محميّة مع خطأ مطبعي", of: "من", perSession: "هذه الجلسة", levelTo: "حتى المستوى", maxLevel: "أعلى مستوى 🎉", streak: "سلسلة", days: "يوم", left: "متبقٍّ لليوم", leftZero: "اكتمل الهدف اليومي 🎯", examNote: "حزمة كلمات جاهزة — اجتز الاختبار لفتح كلمات جديدة", more: "جلسة أخرى", finish: "إلى الدراسة", words: "كلمات", loading: "نجهّز الجلسة…", empty: "لا شيء للتعلّم بعد — أضف كلمات إلى الدراسة" },
}, "LearningSession.T");
